package org.hartford.binsure.enums;

public enum NotificationType {

    // Application flow
    APPLICATION_SUBMITTED,
    APPLICATION_ASSIGNED_TO_UNDERWRITER,
    APPLICATION_UNDER_REVIEW,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    CUSTOMER_ACCEPTED_DECISION,
    CUSTOMER_REJECTED_DECISION,

    // Policy flow
    POLICY_ISSUED,
    POLICY_CANCELLED,
    POLICY_SUSPENDED,
    POLICY_REACTIVATED,
    POLICY_EXPIRING_SOON,

    // Claim flow
    CLAIM_SUBMITTED,
    CLAIM_ASSIGNED_TO_OFFICER,
    CLAIM_UNDER_INVESTIGATION,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_SETTLED,
    CLAIM_APPEALED,

    // Payment flow
    PAYMENT_RECEIVED,
    PAYMENT_PENDING,

    // General
    GENERAL
}
